# Generated by Django 4.0.6 on 2023-04-12 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(blank=True, max_length=600, null=True)),
                ('banner', models.CharField(blank=True, max_length=600, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('link1', models.URLField(blank=True, max_length=1300, null=True, verbose_name='Link 1')),
                ('link2', models.URLField(blank=True, max_length=1300, null=True, verbose_name='Link 2')),
                ('english', models.URLField(blank=True, max_length=1300, null=True, verbose_name='English')),
                ('spoty', models.URLField(blank=True, max_length=1300, null=True, verbose_name='Spotify')),
                ('mediafire', models.URLField(blank=True, max_length=1300, null=True, verbose_name='Mediafire')),
                ('original_name', models.CharField(blank=True, max_length=150, null=True)),
                ('original_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caps.season')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodiePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=600)),
                ('is_default', models.BooleanField(default=True)),
                ('episodie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='caps.episodies')),
            ],
        ),
    ]
